# .github/workflows/test-ci.yml (oder überschreibe ci.yml)
name: Simple CI Test

on:
  push:
    branches: [ main ] # Oder dein Branch-Name

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "GitHub Actions workflow is running!"